export const restaurantsList = [
  {
    id: "1005081",
    name: "Boba Bhai",
    city: "3",
    slugs: {
      restaurant: "boba-bhai-banjara-hills-masab-tank",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/360a3ca1-afc5-4b59-9f30-f83d6aaa7713_1005081.jpg",
    address:
      "8-2-693/2/17, Plot No.17, Road No. 12, Mithila Nagar, Banjara Hills, Hyderabad, Telangana 500034",
    locality: "Banjara Hills",
    areaName: "Mithila Nagar",
    costForTwo: "20000",
    costForTwoMessage: "₹200 FOR TWO",
    cuisines: [
      "Bubble Tea",
      "Burger",
      "Korean",
      "Beverages",
      "Fast Food",
      "Juice and shake",
    ],
    avgRating: 4.3,
    feeDetails: {},
    avgRatingString: "4.3",
    totalRatingsString: "315",
    promoted: true,
    adTrackingId:
      "cid=29494159~p=0~adgrpid=29494159#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=1005081~plpr=SEARCH#RESTAURANT~st=rolls~eid=7b511f4a-0c20-4a2c-acae-435aba380d81~srvts=1748403987957",
    sla: {
      deliveryTime: 43,
      minDeliveryTime: 40,
      maxDeliveryTime: 45,
      lastMileTravel: 6.4,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "40-45 MINS",
      lastMileTravelString: "6.4 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
    campaignId: "29494159",
  },
  {
    id: "233050",
    name: "Faasos - Wraps, Rolls & Shawarma",
    city: "3",
    slugs: {
      restaurant: "faasos-abids-nampally",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/28/68413230-9dc2-459a-91ac-c3950de16632_233050.JPG",
    address:
      "Above HDFC bank J.D Arcade building, 2nd floor beside Little flower Primary school, Abids, Hyderabad- 500001",
    locality: "Beside Little Flower Primary school",
    areaName: "Abids",
    costForTwo: "20000",
    costForTwoMessage: "₹200 FOR TWO",
    cuisines: [
      "Kebabs",
      "Fast Food",
      "Snacks",
      "American",
      "Healthy Food",
      "Desserts",
      "Beverages",
    ],
    avgRating: 4,
    feeDetails: {},
    avgRatingString: "4.0",
    totalRatingsString: "4.8K+",
    sla: {
      deliveryTime: 25,
      minDeliveryTime: 20,
      maxDeliveryTime: 25,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "20-25 MINS",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {
      imageBadges: [
        {
          imageId: "Rxawards/_CATEGORY-Rolls.png",
          description: "Delivery!",
        },
      ],
    },
    aggregatedDiscountInfoV3: {
      header: "ITEMS",
      subHeader: "AT ₹89",
      footerText: "10 DEALS LEFT",
      secondaryHeaderType: "SECONDARY_HEADER_TYPE_USAGE_LIMIT_OFFER",
    },
    ratingSlab: "RATING_SLAB_4",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "1005082",
    name: "Seoul Burgers & Shakes",
    city: "3",
    slugs: {
      restaurant: "seoul-burgers-shakes-banjara-hills-masab-tank",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/b49d6e4f-3282-424a-b868-8db3e00c796e_1005082.jpg",
    address:
      "8-2-693/2/17, Plot No.17, Road No. 12, Mithila Nagar, Banjara Hills, Hyderabad, Telangana 500034",
    locality: "Banjara Hills",
    areaName: "Mithila Nagar",
    costForTwo: "20000",
    costForTwoMessage: "₹200 FOR TWO",
    cuisines: [
      "Burger",
      "Bubble Tea",
      "Fast Food",
      "Beverages",
      "Juice and shake",
    ],
    avgRating: 4.3,
    feeDetails: {},
    avgRatingString: "4.3",
    totalRatingsString: "155",
    promoted: true,
    adTrackingId:
      "cid=29494323~p=2~adgrpid=29494323#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=1005082~plpr=SEARCH#RESTAURANT~st=rolls~eid=80a1e66f-7d2a-4134-bacc-4a7885c8e94e~srvts=1748403987957",
    sla: {
      deliveryTime: 48,
      minDeliveryTime: 45,
      maxDeliveryTime: 50,
      lastMileTravel: 6.4,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "45-50 MINS",
      lastMileTravelString: "6.4 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
    campaignId: "29494323",
  },
  {
    id: "495772",
    name: "Cafe Niloufer",
    city: "3",
    slugs: {
      restaurant: "café-niloufer-himayath-nagar-himayath-nagar",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/19/b56332d3-d749-4b94-b9f3-7e575b8d0ca5_495772.jpg",
    address:
      "M/S. ABR CAFE AND BAKERS PRIVATE LIMITED, 3-5-900, Old MLA Quarters Road, HimayathNagar, Hyderabad-Central Zone, Telangana-500029.",
    locality: "Old Mla Quarters Road",
    areaName: "Himayatnagar",
    costForTwo: "40000",
    costForTwoMessage: "₹400 FOR TWO",
    cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
    avgRating: 4.7,
    feeDetails: {},
    avgRatingString: "4.7",
    totalRatingsString: "26K+",
    sla: {
      deliveryTime: 19,
      minDeliveryTime: 15,
      maxDeliveryTime: 20,
      lastMileTravel: 1.5,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "15-20 MINS",
      lastMileTravelString: "1.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {
      imageBadges: [
        {
          imageId: "Ratnesh_Badges/Rx_Awards_2025/Local%20Gems.png",
          description: "Delivery!",
        },
      ],
    },
    aggregatedDiscountInfoV3: {
      header: "10% OFF",
      subHeader: "ABOVE ₹3000",
      discountTag: "FLAT DEAL",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "56171",
    name: "G.Pulla Reddy - Pure Ghee Sweets",
    city: "3",
    slugs: {
      restaurant: "g-pulla-reddy-sweets-karkhana-kharkhana-trimulgherry",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/27/7918fe4a-af59-4e9b-be48-eb444eef03b0_56171.jpg",
    address:
      "S No. 54, Rajiv Gandhi Rahadari Road, Vasavi Nagar, Karkhana,, Secunderabad, Telangana 500015",
    locality: "Kharkhana",
    areaName: "Kharkhana",
    costForTwo: "30000",
    costForTwoMessage: "₹300 FOR TWO",
    cuisines: ["Sweets", "Desserts", "Snacks"],
    avgRating: 4.6,
    feeDetails: {},
    avgRatingString: "4.6",
    totalRatingsString: "10K+",
    promoted: true,
    adTrackingId:
      "cid=557e4813-633f-4088-8877-8c7196a3b974~p=3~adgrpid=557e4813-633f-4088-8877-8c7196a3b974#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=56171~plpr=SEARCH#RESTAURANT~st=rolls~eid=f90e4b16-509e-4531-9722-9b79436b308c~srvts=1748403987957",
    sla: {
      deliveryTime: 34,
      minDeliveryTime: 30,
      maxDeliveryTime: 35,
      lastMileTravel: 6.8,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "30-35 MINS",
      lastMileTravelString: "6.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    aggregatedDiscountInfo: {
      visible: true,
    },
    badges: {
      imageBadges: [
        {
          imageId: "v1695133679/badges/Pure_Veg111.png",
          description: "pureveg",
        },
      ],
    },
    aggregatedDiscountInfoV2: {
      visible: true,
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
    campaignId: "557e4813-633f-4088-8877-8c7196a3b974",
  },
  {
    id: "569378",
    name: "Protein Chef",
    city: "3",
    slugs: {
      restaurant: "protein-chef-banjara-hills-banjara-hills",
      city: "hyderabad",
    },
    cloudinaryImageId: "c999cb12e0747d3954d7296fc3e06b83",
    address:
      "1ST FLOOR, H.NO. - 6-3-452/A/4, BESIDE LANE OF SWAYAMVAR, PANJAGUTTA, HYDERABAD, Khairatabad Circle No.17 , Hyderabad, Telangana - 500082",
    locality: "Panjagutta",
    areaName: "Banjara Hills",
    costForTwo: "30000",
    costForTwoMessage: "₹300 FOR TWO",
    cuisines: ["North Indian", "Healthy Food", "Snacks"],
    avgRating: 4.4,
    feeDetails: {},
    avgRatingString: "4.4",
    totalRatingsString: "1.6K+",
    sla: {
      deliveryTime: 29,
      minDeliveryTime: 25,
      maxDeliveryTime: 30,
      lastMileTravel: 4.4,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "25-30 MINS",
      lastMileTravelString: "4.4 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "brand",
          fontColor: "#7E808C",
        },
      ],
    },
    aggregatedDiscountInfoV3: {
      header: "ITEMS",
      subHeader: "AT ₹179",
      logoCtx: {
        text: "BENEFITS",
      },
      footerText: "4 DEALS LEFT",
      secondaryHeaderType: "SECONDARY_HEADER_TYPE_USAGE_LIMIT_OFFER",
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "228215",
    name: "Cafe Niloufer Premium Lounge",
    city: "3",
    slugs: {},
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/19/ab61bbdc-0ecd-4cd9-8ea9-4a26564d9dc6_228215.jpg",
    address:
      "Divine Banjara - Amn, 8-2-685/P2 & P3, Road No. 12, Venkateswara Colony, Banjara Hills, Hyderabad, Telangana 500034",
    locality: "Banjara Hills",
    areaName: "Banjara Hills",
    costForTwo: "20000",
    costForTwoMessage: "₹200 FOR TWO",
    cuisines: [],
    avgRating: 4.7,
    feeDetails: {},
    avgRatingString: "4.7",
    totalRatingsString: "47K+",
    sla: {},
    availability: {},
    badges: {},
    aggregatedDiscountInfoV3: {},
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {},
    cartOrderabilityNudgeBanner: {},
    externalRatings: {},
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {},
  },
  {
    id: "481799",
    name: "Peppy Parathas & Rolls By Chai Point",
    city: "3",
    slugs: {
      restaurant: "peppy-paratha-gvk-mall-banjara-hills",
      city: "hyderabad",
    },
    cloudinaryImageId: "bmgng2p89mabre2oldi0",
    address:
      "Shop no 3A, 3rd Floor,food court level 5,road no1 Banjara hills,Hyderabad 500034",
    locality: "GVK Mall",
    areaName: "Banjara Hills",
    costForTwo: "15000",
    costForTwoMessage: "₹150 FOR TWO",
    cuisines: [
      "Bakery",
      "Beverages",
      "Maharashtrian",
      "Snacks",
      "Street Food",
      "South Indian",
      "Punjabi",
      "Chaat",
      "Indian",
      "American",
    ],
    avgRating: 4.1,
    feeDetails: {},
    avgRatingString: "4.1",
    totalRatingsString: "37",
    sla: {
      deliveryTime: 43,
      minDeliveryTime: 40,
      maxDeliveryTime: 45,
      lastMileTravel: 4.9,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "40-45 MINS",
      lastMileTravelString: "4.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "107648",
    name: "Ghrelin - Cafe and Patisserie",
    city: "3",
    slugs: {
      restaurant: "ghrelin-cafe-and-patisserie-king-koti-himayath-nagar",
      city: "hyderabad",
    },
    cloudinaryImageId: "f37orhqt2pa7hxpxfv2q",
    address:
      "6-288/2, Sri Siva Rama Towers , King Koti, Avanti Nagar, Hyderguda., Hyderabad - 500029",
    locality: "Basheerbagh",
    areaName: "Basheerbagh",
    costForTwo: "45000",
    costForTwoMessage: "₹450 FOR TWO",
    cuisines: ["Bakery", "Desserts", "Pizzas", "Pastas", "Italian"],
    avgRating: 4.5,
    feeDetails: {},
    avgRatingString: "4.5",
    totalRatingsString: "8.4K+",
    sla: {
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 30,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "25-30 MINS",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "FREE ITEM",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "4.2",
        ratingCount: "636",
      },
      source: "GOOGLE",
      sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "743516",
    name: "Frankie Hub",
    city: "3",
    slugs: {
      restaurant: "frankies-and-more-uppal-uppal",
      city: "hyderabad",
    },
    cloudinaryImageId: "b563e5a49d17aae69e1856ba85e8f20b",
    address:
      "H No: 2-18-24, opp. survey of India, Prashanthinagar, Prashanth Nagar, Gaddi annaram, Hyderabad, Telangana 500039, India",
    locality: "Prashanthinagar",
    areaName: "Uppal",
    costForTwo: "20000",
    costForTwoMessage: "₹200 FOR TWO",
    cuisines: ["Snacks"],
    avgRating: 3.9,
    feeDetails: {},
    avgRatingString: "3.9",
    totalRatingsString: "158",
    sla: {
      deliveryTime: 63,
      minDeliveryTime: 60,
      maxDeliveryTime: 65,
      lastMileTravel: 10.3,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "60-65 MINS",
      lastMileTravelString: "10.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "UPTO ₹50",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_4",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "--",
      },
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "1123",
    name: "Ci Gusta!",
    city: "3",
    slugs: {
      restaurant: "ci-gusta-kavuri-hills-madhapur-madhapur",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/10/3/d713486a-9532-4123-9eec-426e9606edbd_1123.ss.jpg",
    address:
      "Plot 66, Jyothi Celeste, Kavuri Hills Phase 2,Near Madhapur Police Station.",
    locality: "2nd Phase",
    areaName: "Madhapur",
    costForTwo: "70000",
    costForTwoMessage: "₹700 FOR TWO",
    cuisines: ["Italian", "Desserts", "Continental"],
    avgRating: 4.5,
    feeDetails: {},
    avgRatingString: "4.5",
    totalRatingsString: "8.8K+",
    sla: {
      deliveryTime: 62,
      minDeliveryTime: 60,
      maxDeliveryTime: 65,
      lastMileTravel: 11.4,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "60-65 MINS",
      lastMileTravelString: "11.4 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {
      imageBadges: [
        {
          imageId: "newg.png",
          description: "Gourmet",
        },
      ],
    },
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "4.3",
        ratingCount: "3.8K+",
      },
      source: "GOOGLE",
      sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "1593",
    name: "Sarvi Bakery - Banjara Hills",
    city: "3",
    slugs: {
      restaurant: "sarvi-bakery-banjara-hills",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/2/a22cfc6b-7171-4f72-a0a0-ba41279e633e_1593.jpg",
    address: "Opposite Care Hospital, Road 11, Banjara Hills",
    locality: "Banjara Hills",
    areaName: "Banjara Hills",
    costForTwo: "25000",
    costForTwoMessage: "₹250 FOR TWO",
    cuisines: ["Desserts", "Bakery"],
    avgRating: 4.3,
    feeDetails: {},
    avgRatingString: "4.3",
    totalRatingsString: "14K+",
    sla: {
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 40,
      lastMileTravel: 4.4,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "35-40 MINS",
      lastMileTravelString: "4.4 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "ITEMS",
      subHeader: "AT ₹49",
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "4.0",
        ratingCount: "12K+",
      },
      source: "GOOGLE",
      sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
  {
    id: "689081",
    name: "Third Wave Coffee",
    city: "3",
    slugs: {
      restaurant: "third-wave-coffee-banjara-hills-banjara-hills",
      city: "hyderabad",
    },
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/4/23/ae1a908c-d196-49d2-bc6d-461538ee1b5a_689081.jpg",
    address:
      "Door No 8-2-586/B, 8-2-686/B/A, Ground Floor, G Square Building, Road No. 12, NBT Nagar, Banjara Hills, Hyderabad, Telangana",
    locality: "Banjara Hills",
    areaName: "Banjara Hills",
    costForTwo: "40000",
    costForTwoMessage: "₹400 FOR TWO",
    cuisines: ["Beverages", "Cafe", "Desserts"],
    avgRating: 4.3,
    feeDetails: {},
    avgRatingString: "4.3",
    totalRatingsString: "1.3K+",
    sla: {
      deliveryTime: 29,
      minDeliveryTime: 25,
      maxDeliveryTime: 30,
      lastMileTravel: 5.8,
      serviceability: "SERVICEABLE",
      rainMode: "RAIN_MODE_NONE",
      slaString: "25-30 MINS",
      lastMileTravelString: "5.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      opened: true,
      restaurantClosedMeta: {},
    },
    badges: {},
    aggregatedDiscountInfoV3: {
      header: "20% OFF",
      subHeader: "ABOVE ₹2000",
      discountTag: "FLAT DEAL",
      logoCtx: {
        text: "BENEFITS",
      },
    },
    ratingSlab: "RATING_SLAB_5",
    orderabilityCommunication: {
      title: {},
      subTitle: {},
      message: {},
      customIcon: {},
      commsStyling: {},
    },
    cartOrderabilityNudgeBanner: {
      parameters: {},
      presentation: {},
    },
    externalRatings: {
      aggregatedRating: {
        rating: "4.5",
        ratingCount: "430",
      },
      source: "GOOGLE",
      sourceIconImageId: "v1704440323/google_ratings/rating_google_tag",
    },
    ratingsDisplayPreference: "RATINGS_DISPLAY_PREFERENCE_SHOW_SWIGGY",
    featuredSectionInfo: {
      sectionTitle: "More",
    },
  },
];
